name: cypherlab_workcell
services:
  ###########
  # Modules #
  ###########
  camera_node:
    image: ghcr.io/ad-sdl/camera_module
    container_name: camera_node
    privileged: true # needed for hardware access
    ports:
      - 2003:2003
    command: python -m camera_rest_node --port 2003
    env_file:
      - .env
 
  #####################
  # WEI Core Services #
  #####################
  wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_server
    ports:
      - 8005:8005
    volumes:
      - ./workcells:/workcells
      - ${WEI_DATA_DIR}:/home/app/.wei
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    command: python3 -m wei.server --workcell /workcells/${WORKCELL_FILENAME}
    depends_on:
      - wei_redis

  utilities:
    image: ghcr.io/ad-sdl/wei
    container_name: utility
    ports:
      - 8004:8004
    command: 'python3 -m wei.modules.utility_module
      --port 8004
      --alias utility'

  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 8003:8003
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning
